---
title: "Arne 2019"
author: "Duncan Golicher"
date: "11/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Not for students

```{r}
library(aqm)
library(giscourse)
library(raster)
library(mapview)
library(dplyr)

```


```{r}
data(arne)
data("arne_2019a")
arne_quads<-st_transform(arne_quads,4326)
p2<- arne_quads[,2:4]
p2$Year<-2018
p2$Year[p2$site=="last_year"]<-2017
p2$site<-"Heath"
p2 %>% st_set_geometry(NULL) %>% dt()

```



```{r}


pine_numbers_gps %>% select(c("site","PiNo")) -> p1
p1$site<-as.character(p1$site)
p1$site[p1$site==1]<-"Heath"
p1$site[p1$site==2]<-"Restoration"
p1$Year<-2019
p1$npines<-p1$PiNo
p1$pine_density <-p1$npines/(pi*2^2)
p1<-select(p1,c("Year","site","npines","pine_density"))
p2<-select(p2,c("Year","site","npines","pine_density"))
st_crs(p1)<-st_crs(p2)
p<-rbind(p1,p2)
#mapview(p)

pnts<-data.frame(st_coordinates(p))
pnts<-data.frame(pnts,st_set_geometry(p,NULL))

arne_pines<-pnts
names(arne_pines)[1:2]<-c("lon", "lat")
arne_pines$pine_density<-round(arne_pines$pine_density,3)
save(arne_pines,file="data/arne_pines.rda")
```



